version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: moblab:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
